### ISSUE TITLE
NMAKE : fatal error U1077: '"C:\php\php.exe' : return code '0x1'

### ISSUE THREAD

**Issue by eeliu** [php/setup-php-sdk#7]
> Hello, can you help  me ?

I got `fatal error U1077: '"C:\php\php.exe' ` in nmake, it works fine in my dev environment. 

BYW, I created my dev by `https://github.com/php/php-sdk-binary-tools`

### Description 
```
	"link.exe" @"D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\resp\PINPOINT_PHP_GLOBAL_OBJS.txt" D:\a\pinpoint-c-agent\pinpoint-c-agent\php-dev\lib\php7.lib  kernel32.lib ole32.lib user32.lib advapi32.lib shell32.lib ws2_32.lib Dnsapi.lib psapi.lib bcrypt.lib imagehlp.lib D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\php_pinpoint_php.dll.res /out:D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\php_pinpoint_php.dll /dll /nologo /GUARD:CF /incremental:no /debug /opt:ref,icf /libpath:"\"D:\a\pinpoint-c-agent\pinpoint-c-agent\no\lib\"" /libpath:"D:\a\pinpoint-c-agent\pinpoint-c-agent\php-dev\lib\;D:\a\pinpoint-c-agent\pinpoint-c-agent\php-dev" 
   Creating library D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\php_pinpoint_php.lib and object D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\php_pinpoint_php.exp
EXT pinpoint_php build complete

Microsoft (R) Program Maintenance Utility Version 14.16.27051.0
Copyright (C) Microsoft Corporation.  All rights reserved.

	  "C:\php\php.exe" -d open_basedir= -d output_buffering=0 run-tests.php tests_win32 -p "C:\php\php.exe" -d extension=D:\a\pinpoint-c-agent\pinpoint-c-agent\output\Release\php_pinpoint_php.dll
The system cannot find the path specified.
NMAKE : fatal error U1077: '"C:\php\php.exe' : return code '0x1'
```

Full logging : https://github.com/eeliu/pinpoint-c-agent/actions/runs/10091711770/job/27903819087

### Reproduce 

```
./configure.bat --enable-pinpoint_php --enable-debug-pack --enable-object-out-dir=output
nmake
nmake test TESTS=tests_win32
```

**Comment by cmb69** [comment]
That `U1077` is a very general error code, basically just saying that something went wrong. More relevant is "The system cannot find the path specified.", although it is not immediately clear, which path could not be found. My first guess would be `tests_win32`; does this folder exist? (try `dir tests_win32`)

Also note that this is not the appropriate place to report such issues. I'm not sure, though, to where to direct you. Maybe we can quickly solve this issue here.

**Comment by eeliu** [comment]
@cmb69 

Thanks your quickly reply, I found the reason: 

./configure.bat --enable-pinpoint_php --enable-debug-pack --enable-object-out-dir=output --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}

**Comment by cmb69** [comment]
Great!

Note that you may want to use `nmake test TESTS="--show-diff tests_win32"`; that may help to clarify test failures.
