### ISSUE TITLE
Can `setup-php-sdk` support cache 

### ISSUE THREAD

**Issue by eeliu** [php/setup-php-sdk#8]
## Background 

I found it takes lots of time in setup-php-sdk 

![image](https://github.com/user-attachments/assets/64a7e35b-b00f-48d0-9684-8ea6c41d968d)

Can we use cache to speed up this progress ? and how ?

**Comment by cmb69** [comment]
> Can we use cache to speed up this progress ? and how ?

Good question! I also wonder for a long time how that can be done from within the action. Maybe have a look at https://github.com/actions/cache.
